"""initial schema

Revision ID: 8f14a11346c4
Revises: 
Create Date: 2023-12-08 19:03:54.320856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8f14a11346c4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('willow_clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mac_addr', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mac_addr')
    )
    op.create_table('willow_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_type', sa.Enum('config', 'multinet', 'nvs', name='willowconfigtype'), nullable=False),
    sa.Column('config_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('config_namespace', sa.Enum('WAS', 'WIFI', name='willowconfignamespacetype'), nullable=True),
    sa.Column('config_value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_type', 'config_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('willow_config')
    op.drop_table('willow_clients')
    # ### end Alembic commands ###
